version: 2
updates:
- package-ecosystem: nuget
  directory: "/TechDebtIdentification/TechDebtIdentification.Web"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
