name: "Technical Debt ID CI/CD"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      dotNetVersion: net5
      dotNetConfiguration: Release

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100      
    #Build and test service   
    - name: Run automated unit and integration tests
      run: dotnet test TechDebtIdentification/TechDebtIdentification.Tests/TechDebtIdentification.Tests.csproj --configuration ${{ env.dotNetConfiguration }}
    #Publish dotnet objects
    - name: publish console app
      run: dotnet publish TechDebtIdentification/TechID.App/TechID.csproj --configuration ${{ env.dotNetConfiguration }}
    #Publish build artifacts to GitHub
    - name: Upload website build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: app
        path: TechDebtIdentification/TechID.App/bin/${{ env.dotNetConfiguration }}/${{ env.dotNetVersion }}/publish
